# 01 - Experiment Objective

Determine which embedding model gives this production RAG system the best retrieval quality, latency, and resource profile. The initial benchmark uses English enterprise-style content; multilingual English/Urdu, Arabic, and other enterprise content should be added before final production selection.

# 02 - Environment Setup

Colab can use a GPU runtime for model inference. The benchmark records the selected device and keeps model downloads outside the laptop environment.

In [11]:
import os
import time

# Avoid Xet CDN checkpoint reconstruction failures in Hugging Face Hub downloads.
os.environ["HF_HUB_DISABLE_XET"] = "1"
os.environ["HF_HUB_DOWNLOAD_TIMEOUT"] = "300"
os.environ["HF_HUB_ETAG_TIMEOUT"] = "60"

import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer

print(f"NumPy: {np.__version__}")

NumPy: 2.5.3

# 03 - Dataset Preparation

The initial benchmark is intentionally small and English-only. A serious evaluation should expand this with representative enterprise documents, queries, and multilingual coverage.

In [2]:
documents = [
    "Employees receive twenty four annual leave days.",
    "Employees must submit leave requests through the HR portal.",
    "Medical leave requires supporting medical documentation.",
    "The IT department manages employee laptop provisioning.",
    "Password resets must be requested through the service desk.",
    "Managers approve annual leave requests.",
]

queries = [
    "How many annual leave days do employees receive?",
    "How do employees submit leave requests?",
    "What is required for medical leave?",
    "Who manages employee laptops?",
    "How do I reset my password?",
    "Who approves annual leave?",
]

relevant_documents = {
    0: [0],
    1: [1],
    2: [2],
    3: [3],
    4: [4],
    5: [5],
}

benchmark = pd.DataFrame({"query": queries})
benchmark

                                              query
0  How many annual leave days do employees receive?
1           How do employees submit leave requests?
2               What is required for medical leave?
3                     Who manages employee laptops?
4                       How do I reset my password?
5                        Who approves annual leave?

# 04 - Candidate Embedding Models

The initial candidates cover a compact general-purpose model and two BGE models. Popularity is not a selection criterion; the benchmark decides.

In [5]:
MODELS = [
    "sentence-transformers/all-MiniLM-L6-v2",
    "BAAI/bge-small-en-v1.5",
    "BAAI/bge-base-en-v1.5",
]

MODELS

['sentence-transformers/all-MiniLM-L6-v2',
 'BAAI/bge-small-en-v1.5',
 'BAAI/bge-base-en-v1.5']

# 05 - Embedding Generation

Start with `all-MiniLM-L6-v2`; later loop over `MODELS` and store each model's metrics.

In [3]:
device = "cpu"

model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2",
    device=device,
)

print("Device:", model.device)

document_embeddings = model.encode(
    documents,
    normalize_embeddings=True,
    show_progress_bar=True,
)
query_embeddings = model.encode(
    queries,
    normalize_embeddings=True,
    show_progress_bar=True,
)

print("Document embeddings:", document_embeddings.shape)
print("Query embeddings:", query_embeddings.shape)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 7222.73it/s]

Device: cpu

Batches: 100%|██████████| 1/1 [00:00<00:00,  6.55it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 26.98it/s]

Document embeddings: (6, 384)
Query embeddings: (6, 384)

# 06 - Retrieval Benchmark

Normalized embeddings make the dot product equivalent to cosine similarity for this benchmark.

In [6]:
similarities = query_embeddings @ document_embeddings.T

print("Similarity matrix:", similarities.shape)


def retrieve(
    query_index: int,
    k: int = 5,
):
    scores = similarities[query_index]
    ranked_indices = np.argsort(scores)[::-1]
    return ranked_indices[:k]


retrieve(0, k=3)

Similarity matrix: (6, 6)

array([0, 5, 1])

# 07 - Recall@K

In [7]:
def recall_at_k(
    similarities,
    ground_truth,
    k,
):
    hits = 0

    for query_index, relevant in ground_truth.items():
        ranked = np.argsort(similarities[query_index])[::-1][:k]

        if any(index in relevant for index in ranked):
            hits += 1

    return hits / len(ground_truth)


for k in [1, 3, 5]:
    print(
        f"Recall@{k}:",
        recall_at_k(
            similarities,
            relevant_documents,
            k,
        ),
    )

Recall@1: 1.0
Recall@3: 1.0
Recall@5: 1.0

# 08 - MRR

In [8]:
def mean_reciprocal_rank(
    similarities,
    ground_truth,
):
    reciprocal_ranks = []

    for query_index, relevant in ground_truth.items():
        ranked = np.argsort(similarities[query_index])[::-1]

        reciprocal_rank = 0.0

        for rank, index in enumerate(
            ranked,
            start=1,
        ):
            if index in relevant:
                reciprocal_rank = 1 / rank
                break

        reciprocal_ranks.append(reciprocal_rank)

    return np.mean(reciprocal_ranks)


mrr = mean_reciprocal_rank(
    similarities,
    relevant_documents,
)

print("MRR:", mrr)

MRR: 1.0

# 09 - Latency

In [9]:
def measure_query_latency(model, query_batch, runs=5):
    latencies = []

    for _ in range(runs):
        start = time.perf_counter()
        model.encode(query_batch, normalize_embeddings=True, show_progress_bar=False)
        latencies.append(time.perf_counter() - start)

    return {
        "mean_seconds": float(np.mean(latencies)),
        "p95_seconds": float(np.percentile(latencies, 95)),
    }


latency = measure_query_latency(model, queries)
latency

{'mean_seconds': 0.06959232000008342, 'p95_seconds': 0.14929749999791964}

# 10 - Memory

In [10]:
memory = {
    "parameter_count": sum(parameter.numel() for parameter in model.parameters()),
    "embedding_dimension": int(document_embeddings.shape[1]),
    "device": str(model.device),
}

pd.Series(memory)

parameter_count        22713216
embedding_dimension         384
device                      cpu
dtype: object

# 11 - Results

In [12]:
results = []

for model_name in MODELS:
    print(f"Testing {model_name}")

    start = time.perf_counter()

    model = SentenceTransformer(model_name)

    document_embeddings = model.encode(
        documents,
        normalize_embeddings=True,
        show_progress_bar=False,
    )

    query_embeddings = model.encode(
        queries,
        normalize_embeddings=True,
        show_progress_bar=False,
    )

    elapsed = time.perf_counter() - start

    similarities = query_embeddings @ document_embeddings.T

    results.append(
        {
            "model": model_name,
            "recall_at_1": recall_at_k(
                similarities,
                relevant_documents,
                1,
            ),
            "recall_at_3": recall_at_k(
                similarities,
                relevant_documents,
                3,
            ),
            "recall_at_5": recall_at_k(
                similarities,
                relevant_documents,
                5,
            ),
            "mrr": mean_reciprocal_rank(
                similarities,
                relevant_documents,
            ),
            "experiment_seconds": elapsed,
            "embedding_dimension": document_embeddings.shape[1],
        }
    )

results_df = pd.DataFrame(results)
results_df

Testing sentence-transformers/all-MiniLM-L6-v2

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1514.81it/s]

Testing BAAI/bge-small-en-v1.5

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 1320.83it/s]

Testing BAAI/bge-base-en-v1.5

Error while downloading from https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/model.safetensors: The read operation timed out
Trying to resume download...
Error while downloading from https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/model.safetensors: _ssl.c:1015: The handshake operation timed out
Trying to resume download...
Error while downloading from https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/model.safetensors: [Errno 11001] getaddrinfo failed
Trying to resume download...
Error while downloading from https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/model.safetensors: The read operation timed out
Trying to resume download...
Error while downloading from https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/model.safetensors: The read operation timed out
Trying to resume download...
Error while downloading from https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/model.safetensors: The read operation timed out
Trying to resume download...
Error while downloading from https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/model.safetensors: [Errno 11001] getaddrinfo failed
Trying to resume download...
Error while downloading from https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/model.safetensors: The read operation timed out
Trying to resume download...
Error while downloading from https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/model.safetensors: [Errno 11001] getaddrinfo failed
Trying to resume download...
Error while downloading from https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/model.safetensors: The read operation timed out
Trying to resume download...
Error while downloading from https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/model.safetensors: The read operation timed out
Trying to resume download...
Error while downloading from https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/model.safetensors: [Errno 11001] getaddrinfo failed
Trying to resume download...
Error while downloading from https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/model.safetensors: The read operation timed out
Trying to resume download...
Error while downloading from https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/model.safetensors: The read operation timed out
Trying to resume download...
Error while downloading from https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/model.safetensors: The read operation timed out
Trying to resume download...
Error while downloading from https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/model.safetensors: The read operation timed out
Trying to resume download...
Error while downloading from https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/model.safetensors: The read operation timed out
Trying to resume download...
Error while downloading from https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/model.safetensors: [Errno 11001] getaddrinfo failed
Trying to resume download...
Error while downloading from https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/model.safetensors: The read operation timed out
Trying to resume download...
Error while downloading from https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/model.safetensors: _ssl.c:1015: The handshake operation timed out
Trying to resume download...
Error while downloading from https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/model.safetensors: The read operation timed out
Trying to resume download...
Error while downloading from https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/model.safetensors: The read operation timed out
Trying to resume download...
Error while downloading from https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/model.safetensors: The read operation timed out
Trying to resume download...
Error while downloading from https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/model.safetensors: The read operation timed out
Trying to resume download...
Error while downloading from https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/model.safetensors: [Errno 11001] getaddrinfo failed
Trying to resume download...
c:\Projects\enterprise-ai-knowledge-assistant\.venv-gpu\Lib\site-packages\huggingface_hub\file_download.py:150: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Muqadas Rajpoot\.cache\huggingface\hub\models--BAAI--bge-base-en-v1.5. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 751.84it/s]

,model,recall_at_1,recall_at_3,recall_at_5,mrr,experiment_seconds,embedding_dimension
0,sentence-transformers/all-MiniLM-L6-v2,1.0,1.0,1.0,1.0,9.052555,384
1,BAAI/bge-small-en-v1.5,1.0,1.0,1.0,1.0,9.735125,384
2,BAAI/bge-base-en-v1.5,1.0,1.0,1.0,1.0,988.323232,768

## Prototype Limitations

This six-question benchmark establishes the methodology only. The final evaluation should include 500+ question/document pairs across HR, IT, Finance, Procurement, Operations, Policies, Compliance, and technical documentation.

## Engineering Decision Criteria

The production choice should balance retrieval quality, latency, embedding dimension, GPU/CPU requirements, cost, deployment complexity, and language coverage. Multilingual English/Urdu, Arabic, and other enterprise content should be benchmarked before final selection.

# 12 - Model Selection

Select the production candidate from measured retrieval quality first, then use latency and memory as constraints. Do not select by model popularity.

In [13]:
selected_model = results_df.sort_values(
    ["recall_at_5", "mrr", "experiment_seconds"],
    ascending=[False, False, True],
).iloc[0]

print("Selected model:", selected_model["model"])
selected_model

Selected model: sentence-transformers/all-MiniLM-L6-v2

model                  sentence-transformers/all-MiniLM-L6-v2
recall_at_1                                               1.0
recall_at_3                                               1.0
recall_at_5                                               1.0
mrr                                                       1.0
experiment_seconds                                   9.052555
embedding_dimension                                       384
Name: 0, dtype: object

# 13 - Export Configuration

Export the measured winner into the application configuration only after the larger, representative benchmark and multilingual evaluation are complete.

In [15]:
export_config = {
    "EMBEDDING_PROVIDER": "sentence_transformers",
    "EMBEDDING_MODEL": str(selected_model["model"]),
    "EMBEDDING_DIMENSION": int(selected_model["embedding_dimension"]),
}

export_config

{'EMBEDDING_PROVIDER': 'sentence_transformers',
 'EMBEDDING_MODEL': 'sentence-transformers/all-MiniLM-L6-v2',
 'EMBEDDING_DIMENSION': 384}